variables:
  GIT_SUBMODULE_STRATEGY: recursive


default:
  image: python:3.8


before_script:
  - pip install --upgrade pip
  - pip install pytest
  - pip install -r requirements.txt


# test saqc with python 3.7
python37:
  stage: test
  image: python:3.7
  script:
    - pytest tests/core tests/flagger tests/funcs
    - python -m saqc --config ressources/data/config_ci.csv --data ressources/data/data.csv --outfile /tmp/test.csv


# test saqc with python 3.8
python38:
  stage: test
  script:
    - pytest tests/core tests/flagger tests/funcs
    - python -m saqc --config ressources/data/config_ci.csv --data ressources/data/data.csv --outfile /tmp/test.csv


# test lib saqc
testLib:
  stage: test
  script:
    - pytest tests/lib


# fuzzy testing saqc
fuzzy:
  allow_failure: true
  stage: test
  script:
    - pytest tests/fuzzy


# make (visual) coverage in gitlab merge request diff's
coverage:
  allow_failure: true
  stage: test

  script:
    - pip install pytest-cov coverage
    - pytest --cov=saqc tests/core tests/flagger tests/funcs
  after_script:
    - coverage xml

  # regex to find the coverage percentage in the job output
  coverage: '/^TOTAL.+?(\d+\%)$/'

  artifacts:
    when: always
    reports:
      cobertura: coverage.xml


# make html docu with sphinx
pages:
  stage: deploy
  script:
    - cd sphinx-doc/
    - pip install -r requirements_sphinx.txt
    - make doc
    - cp -r _build/html ../public
  artifacts:
    paths:
      - public
  only:
    - develop
