before_script:
  - apt-get update -qq
  - apt-get install -y -qq python3.6  python3-pip git
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"


test:python35:
  script:
    - pyenv install 3.5.9
    - pyenv shell 3.5.9
    - python -m pytest test


test:python36:
  script:
    - pyenv install 3.6.9
    - pyenv shell 3.6.9
    - python -m pytest test


test:python37:
  script:
    - pyenv install 3.7.5
    - pyenv shell 3.7.5
    - python -m pytest test


test:python38:
  script:
    - pyenv install 3.8.0
    - pyenv shell 3.8.0
    - python -m pytest test
