# SPDX-FileCopyrightText: 2021 Helmholtz-Zentrum für Umweltforschung GmbH - UFZ
#
# SPDX-License-Identifier: GPL-3.0-or-later

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
# trigger an Error for unknown mark's
addopts = "--strict-markers"
testpaths = "tests"
markers = "slow: marks tests as slow (deselect with '-m \"not slow\"')"

